import type { AppModule } from '../types/architecture';

// Solar CRM - Green NRG Admin Dashboard Modules
export const moduleMap: AppModule[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    description: 'Live KPI and operational metrics overview.',
    category: 'operational',
    priority: 'foundation',
    priorityOrder: 1,
    allowedRoles: ['developer', 'admin', 'operator'],
    accessStrategy: 'permission-based',
    pages: [
      {
        id: 'dashboard-home',
        label: 'Dashboard',
        kind: 'overview',
        path: '/dashboard',
        notes: 'Main KPI dashboard with date filters.',
      },
    ],
    notes: 'Main operational dashboard for all roles.',
  },
  {
    id: 'clients',
    label: 'Clients',
    description: 'Client records and relationship history.',
    category: 'operational',
    priority: 'high',
    priorityOrder: 2,
    allowedRoles: ['developer', 'admin', 'operator'],
    accessStrategy: 'permission-based',
    pages: [
      {
        id: 'clients-list',
        label: 'Clients',
        kind: 'list',
        path: '/clients',
      },
      {
        id: 'clients-detail',
        label: 'Client Detail',
        kind: 'detail',
        path: '/clients/:id',
      },
      {
        id: 'clients-create',
        label: 'Create Client',
        kind: 'create',
        path: '/clients/new',
      },
    ],
    notes: 'Client management (converted leads).',
  },
  {
    id: 'webapp-clients',
    label: 'WebApp Clients',
    description: 'Clients that arrived through the Telegram WebApp store.',
    category: 'operational',
    priority: 'high',
    priorityOrder: 2.5,
    allowedRoles: ['developer', 'admin', 'operator'],
    accessStrategy: 'permission-based',
    pages: [
      {
        id: 'webapp-clients-list',
        label: 'WebApp Clients',
        kind: 'list',
        path: '/webapp-clients',
      },
    ],
    notes: 'WebApp-sourced clients (metadata.webapp_user_id) kept separate from the main client queue.',
  },
  {
    id: 'products',
    label: 'Products',
    description: 'Product catalog and inventory.',
    category: 'operational',
    priority: 'high',
    priorityOrder: 3,
    allowedRoles: ['developer', 'admin', 'operator'],
    accessStrategy: 'permission-based',
    pages: [
      {
        id: 'products-list',
        label: 'Products',
        kind: 'list',
        path: '/products',
      },
      {
        id: 'products-detail',
        label: 'Product Detail',
        kind: 'detail',
        path: '/products/:id',
      },
      {
        id: 'products-create',
        label: 'Create Product',
        kind: 'create',
        path: '/products/new',
      },
    ],
    notes: 'Solar products and services catalog.',
  },
  {
    id: 'chats',
    label: 'Chats',
    description: 'Client communication and messaging.',
    category: 'operational',
    priority: 'medium',
    priorityOrder: 4,
    allowedRoles: ['developer', 'admin', 'operator'],
    accessStrategy: 'permission-based',
    pages: [
      {
        id: 'chats-list',
        label: 'Chat Sessions',
        kind: 'list',
        path: '/chats',
      },
      {
        id: 'chats-detail',
        label: 'Chat Window',
        kind: 'detail',
        path: '/chats/:id',
      },
    ],
    notes: 'Real-time client messaging with WebSocket support.',
  },
  {
    id: 'contracts',
    label: 'Contracts',
    description: 'Contract management and document handling.',
    category: 'operational',
    priority: 'high',
    priorityOrder: 5,
    allowedRoles: ['developer', 'admin', 'operator'],
    accessStrategy: 'permission-based',
    pages: [
      {
        id: 'contracts-list',
        label: 'Contracts',
        kind: 'list',
        path: '/contracts',
      },
      {
        id: 'contracts-detail',
        label: 'Contract Detail',
        kind: 'detail',
        path: '/contracts/:id',
      },
      {
        id: 'contracts-create',
        label: 'Create Contract',
        kind: 'create',
        path: '/contracts/new',
      },
    ],
    notes: 'Contract management with file upload and recalculation.',
  },
  {
    id: 'notifications',
    label: 'Notifications',
    description: 'System notifications and alerts.',
    category: 'operational',
    priority: 'medium',
    priorityOrder: 6,
    allowedRoles: ['developer', 'admin', 'operator'],
    accessStrategy: 'permission-based',
    pages: [
      {
        id: 'notifications-list',
        label: 'Notifications',
        kind: 'list',
        path: '/notifications',
      },
    ],
    notes: 'Alert and workflow notifications.',
  },
  {
    id: 'integrations',
    label: 'Integrations',
    description: 'Third-party integrations and API setup.',
    category: 'system',
    priority: 'low',
    priorityOrder: 7,
    allowedRoles: ['developer'],
    accessStrategy: 'static-role-based',
    pages: [
      {
        id: 'integrations-list',
        label: 'Integrations',
        kind: 'configuration',
        path: '/integrations',
      },
    ],
    notes: 'Developer-only module for managing integrations.',
  },
  {
    id: 'ai-settings',
    label: 'AI Settings',
    description: 'AI agent configuration and behavior.',
    category: 'intelligence',
    priority: 'low',
    priorityOrder: 8,
    allowedRoles: ['developer'],
    accessStrategy: 'static-role-based',
    pages: [
      {
        id: 'ai-settings-overview',
        label: 'AI Settings',
        kind: 'configuration',
        path: '/ai-settings',
      },
    ],
    notes: 'Developer-only AI configuration.',
  },
  {
    id: 'subsidy-settings',
    label: 'Subsidy Settings',
    description: 'Government subsidy percent, limits and calculator settings.',
    category: 'system',
    priority: 'medium',
    priorityOrder: 7.5,
    allowedRoles: ['developer', 'admin'],
    accessStrategy: 'static-role-based',
    pages: [
      {
        id: 'subsidy-settings-overview',
        label: 'Subsidy Settings',
        kind: 'configuration',
        path: '/subsidy-settings',
      },
    ],
    notes: 'Admin-managed subsidy config consumed by the public calculator API.',
  },
  {
    id: 'logs',
    label: 'Logs',
    description: 'System and API audit logs.',
    category: 'system',
    priority: 'low',
    priorityOrder: 9,
    allowedRoles: ['developer'],
    accessStrategy: 'static-role-based',
    pages: [
      {
        id: 'logs-list',
        label: 'Logs',
        kind: 'log',
        path: '/logs',
      },
    ],
    notes: 'Developer-only audit and system logs.',
  },
  {
    id: 'users',
    label: 'Users',
    description: 'User account and access management.',
    category: 'system',
    priority: 'low',
    priorityOrder: 10,
    allowedRoles: ['developer', 'admin'],
    accessStrategy: 'permission-based',
    pages: [
      {
        id: 'users-list',
        label: 'Users',
        kind: 'list',
        path: '/users',
      },
      {
        id: 'users-detail',
        label: 'User Detail',
        kind: 'detail',
        path: '/users/:id',
      },
      {
        id: 'users-create',
        label: 'Create User',
        kind: 'create',
        path: '/users/new',
      },
    ],
    notes: 'Admin and developer only - user management.',
  },
  {
    id: 'operator-kpi',
    label: 'Operator KPI',
    description: 'Operator performance metrics and distributions.',
    category: 'system',
    priority: 'low',
    priorityOrder: 11,
    allowedRoles: ['developer', 'admin', 'operator'],
    accessStrategy: 'permission-based',
    pages: [
      {
        id: 'operator-kpi-overview',
        label: 'Operator KPI',
        kind: 'overview',
        path: '/operator-kpi',
      },
    ],
    notes: 'Operator KPI page based on operator statistics API.',
  },
];

export const crossSystemCapabilities = [
  'Authentication & Authorization',
  'Global Notifications',
  'Responsive Admin Shell',
  'Role-Based Navigation',
  'Permission-Based Route Guards',
] as const;

export const implementationOrder = [...moduleMap].sort(
  (left, right) => left.priorityOrder - right.priorityOrder,
);
